### ISSUE TITLE
DESARROLLO ( Henry )

### ISSUE THREAD

**Issue by AdrianaPTC** [CarsOk/Preescolar_Ilusiones#14]
Como: empresario 
Quiero: Habilitar una carpeta 
Para: ingresar los avances del proyecto 

Criterios de Aceptación 
 ✓ ingresar actualizaciones semanales

**Comment by NAYA28cc** [comment]
[talleractualizado.txt](https://github.com/CarsOk/corteva_agriscience/files/8665562/talleractualizado.txt)

**Comment by NAYA28cc** [comment]
[talleractualizado-.txt](https://github.com/CarsOk/corteva_agriscience/files/8666230/talleractualizado-.txt)
